### ISSUE TITLE
Error "crashing" app

### ISSUE THREAD

**Issue by Futureglobe** [ZeroX-DG/SnippetStore#1]
Hi, i was going through your app and noticed a error causing the app to be unusable. I*m not sure if you are aware of this problem.

Steps to re-produce: 

#1: Click at the "+" icon the create a new note and select "Multifile Snippet"
#2: Click on the "New file" area and create for example 3 of them.

Now try to delete all of them and on the way you will see the error causing this screen for the user: 
![error](https://user-images.githubusercontent.com/27356972/42692643-a26061b0-86ac-11e8-8f55-0c5443f2d791.png)

I just though i tell you about this problem :)
But for a 17 year old i must say good job keep it going 👍

**Comment by ZeroX-DG** [comment]
Hey @Futureglobe , I have released v0.2.2 which include the fix for your bug, can you confirm it?

**Comment by Futureglobe** [comment]
First of all great response time :) I downloaded the new version and it seems to fixed the problem. But as normal in software development there is now another error: 

![image](https://user-images.githubusercontent.com/27356972/42765623-b83b1264-8918-11e8-86dd-70a82cce5943.png)

**Comment by ZeroX-DG** [comment]
Hmm...Can you provide some details about this new bug?

**Comment by Futureglobe** [comment]
Not really it occurs the same way the one before did.

**Comment by ZeroX-DG** [comment]
Thank you very much @Futureglobe , I've fixed the bug (I hope so :smile: ), here is the pre-release, can you confirm that the bug is fixed?
https://github.com/ZeroX-DG/SnippetStore/releases/tag/v0.2.3

**Comment by Futureglobe** [comment]
Yes the bug is now fixed. Good job 👍

**Comment by ZeroX-DG** [comment]
Thank you very much for reporting this bug, I'll release it tomorrow
