### ISSUE TITLE
OSX hotkey issue

### ISSUE THREAD

**Issue by Aweryn** [ZeroX-DG/SnippetStore#10]
I built a mac os package and everything seems to run fine but instead of CmD+N to create a new snippet the app opens a new snippet dialog every time you press just "N" key.

-> Thus cannot type anything that includes the character N

**Comment by ZeroX-DG** [comment]
Thanks for reporting, I'll try to fix it.

**Comment by ZeroX-DG** [comment]
Fixed [347339b](https://github.com/ZeroX-DG/SnippetStore/commit/347339b) (Unreleased)
