### ISSUE TITLE
Blank Screen?

### ISSUE THREAD

**Issue by rnehring** [ZeroX-DG/SnippetStore#11]
Added my 4th snippet, a plaintext snippet for Lorem Ipsum, and the screen just went blank.  Opening the devtool shows some js issues.  Really like this program, hoping it's a simple fix!  Tried reloading the application and the using the "Reload Window" option and still blank.
![snippetstore](https://user-images.githubusercontent.com/136054/44270091-6ef63c00-a204-11e8-8ead-8e833db69051.jpg)

Running v.0.2.6 on Windows 10 Pro.

**Comment by ZeroX-DG** [comment]
Don't worry, I have investigated the problem and I think it's gonna be a simple fix

**Comment by ZeroX-DG** [comment]
@rnehring SnippetStore v0.2.7 is out now and your bug is fixed. Thank you for reporting.
