### ISSUE TITLE
Filtering for languages with more than one word

### ISSUE THREAD

**Issue by 4gray** [ZeroX-DG/SnippetStore#12]
First of all I would like to thank you for this application!

I have found a small filtering bug. If the language name contains more than 1 word (e.g. "Common List", "Plain Text" etc.) application returns empty snippet list.

![snippetstore 2018-08-26 10-55-21](https://user-images.githubusercontent.com/1503032/44626546-980e7f00-a91e-11e8-884c-a8576546535d.jpg)
![snippetstore 2018-08-26 10-54-57](https://user-images.githubusercontent.com/1503032/44626547-98a71580-a91e-11e8-960e-b7aed0b3f570.jpg)

**Comment by ZeroX-DG** [comment]
Thank you for reporting, I'll fix this soon!

**Comment by ZeroX-DG** [comment]
Fixed in the latest release v0.2.8. When you click on the language on the left bar, the white space in language name will be replaced with `_`. So be sure to add `_` between words when you type the language name by hand.
