### ISSUE TITLE
Mac - Incorrect Tray Icon Size

### ISSUE THREAD

**Issue by Eric-Jackson** [ZeroX-DG/SnippetStore#14]
On Mac, the tray icon is displaying at the full 512px. 

I've used the following code on line 7 of `app-tray.js` to correct the issue:

```js
  let icon
  if (process.platform === 'darwin') {
    icon = 'icon18.png'
  } else {
    icon = 'icon512.png'
  }

  tray = new Tray(
    nativeImage.createFromPath(
      path.join(__dirname, '..', 'resources', 'icon', icon)
    )
  )
```

`icon18.png` is an 18x18px image.

**Comment by ZeroX-DG** [comment]
Thank you for reporting, I didn't no icon size is not limited on MacOS, I don't have a Mac to test this haha. Anyway, I'll fix this issue soon, thanks!

**Comment by PDDStudio** [comment]
@ZeroX-DG How can people with a Mac actually assist you? (Beside testing the app for that platform by using it)

I cloned the repo, installed the dependencies & run the build commmand for Mac as stated in the Readme: `npm run dist:mac`

Everything worked straight out of the box for me and I was also able to run the app (without any errors so far)

**Comment by ZeroX-DG** [comment]
I'm currently don't have much time for this project. I'll be back in a few months and maybe I'll find mac user to help develop this project. @PDDStudio If you're interested in this project, I'll contact you when I'm back and we can collaborate on this project.

**Comment by Eric-Jackson** [comment]
@PDDStudio the tray icon isn't enlarged for you? What version of Mac are you on?

**Comment by ZeroX-DG** [comment]
@Eric-Jackson can you confirm that this bug had been fixed in the latest release ?

**Comment by Eric-Jackson** [comment]
@ZeroX-DG yes it's working now. However I'm not sure if you want the icon to be blue, up to you!

![screen shot 2018-10-02 at 9 05 24 am](https://user-images.githubusercontent.com/1268260/46350287-6629c000-c622-11e8-92a3-3edb21a21615.png)

**Comment by ZeroX-DG** [comment]
I'll fix it when I have the time, but for now, I'm closing this issue. Thank you for reporting!
