### ISSUE TITLE
Multi-file Snippet creation bug

### ISSUE THREAD

**Issue by nickfmc** [ZeroX-DG/SnippetStore#16]
When Trying to create a multi-part snippet on Windows, when clicking in the Snippet content "new file" area it opens up a blank screen. With no way back, Dev tools shows an error in main.js on this page.

**Comment by ZeroX-DG** [comment]
Thank you for reporting. Can you take a picture of the dev tool error and post it here?

**Comment by onetrev** [comment]
I have the same issue. Here's my screenshot.

![image](https://user-images.githubusercontent.com/597601/46712087-0f179100-cc9b-11e8-867d-f7b5d273a8f0.png)

**Comment by ZeroX-DG** [comment]
Thanks, I can reproduce the problem I'll fix this bug soon

**Comment by ZeroX-DG** [comment]
I've fixed this bug. This will not happen in the next version (I hope so :smile: )

**Comment by ZeroX-DG** [comment]
@nickfmc @onetrev I have released v0.2.9-pre to fix this issue, please tell me if this issue still exists.
https://github.com/ZeroX-DG/SnippetStore/releases/tag/v0.2.9

**Comment by onetrev** [comment]
Works perfectly now. Awesome, thank you!  I think this issue can be closed now. This is such a great feature of your app. I have a few more little bugs / issues to post, will do as soon as I can.
