### ISSUE TITLE
PHP snippets without PHP tags - no code highlighting

### ISSUE THREAD

**Issue by onetrev** [ZeroX-DG/SnippetStore#17]
I noticed that if you have PHP snippets that don't have the PHP tags around them, then you lose the code highlighting. This is definitely needed in some cases where you know that is code that always goes into an open PHP section. See below:

![capture-php](https://user-images.githubusercontent.com/597601/47197368-8d69e680-d3b1-11e8-9833-c4c192235220.PNG)

**Comment by ZeroX-DG** [comment]
Maybe I'll add an option in the setting to allow PHP code without `<?php` and `?>`. Thanks for reporting

**Comment by ZeroX-DG** [comment]
This feature will be available in the next version. Thank you for your suggestion! :tada:

**Comment by arcturus140** [comment]
I seem to have this issue, too. How can I enable syntax highlighting without `<? ?>` tags?

**Comment by ZeroX-DG** [comment]
Fixed in the latest release:
https://github.com/ZeroX-DG/SnippetStore/releases/tag/v0.2.10.
@arcturus140 @onetrev You can look at this tweet to know how to use this feature.
https://twitter.com/ZeroX_Hung/status/1054731082808070145
