### ISSUE TITLE
Custom code highlighting

### ISSUE THREAD

**Issue by patrickTingen** [ZeroX-DG/SnippetStore#20]
Hi, first thanks for this cool tool. 

I am still exploring and testing it, but one thing that would benefit me is support for additional programming languages. I work in Progress 4GL (also known as OpenEdge ABL) and since it is a bit obscure I am not surprised that it is not supported. Are there any ways / plans to add extra languages?

**Comment by ZeroX-DG** [comment]
Snippet Store is currently using [CodeMirror](https://github.com/codemirror/CodeMirror) and will support any language that [CodeMirror](https://github.com/codemirror/CodeMirror) support. If you want your language to be available you should contribute it to CodeMirror.
I'm currently doesn't have any plan on adding extra languages sorry.

**Comment by patrickTingen** [comment]
No problem, I will see if I can add my language to CodeMirror. Thanks!
