### ISSUE TITLE
[bug] A JavaScript error on export abort

### ISSUE THREAD

**Issue by arcturus140** [ZeroX-DG/SnippetStore#23]
![snippetstoreerror](https://user-images.githubusercontent.com/44707562/48649830-e007e400-e9eb-11e8-8eb9-00a094acb2a5.png)

# Steps to replicate
1. Snippet / export a snippet
2. select `Cancel`

cancel import works, though.

OS and Version: 16.04 Ubuntu

**Comment by ZeroX-DG** [comment]
I remember I fixed this bug hundreds of times already. Why is it still here :cry: Anyway, this is an easy fix haha.
The `paths` variable is undefined if the user cancels export.
https://github.com/ZeroX-DG/SnippetStore/blob/5b6644b112fe4acf6c1b57d40d0d2918366710a9/app/app-menu.js#L74-L77

**Comment by ZeroX-DG** [comment]
Fixed in the latest release:
https://github.com/ZeroX-DG/SnippetStore/releases/tag/v0.2.10
