### ISSUE TITLE
Package  cryptiles Insufficient Entropy

### ISSUE THREAD

**Issue by magussiro** [ZeroX-DG/SnippetStore#28]
I am tring using npm audit to check if any discovered vulenity in dependency package, after I ran
"npm audit fix --force" ,It's still have this security issue:
OS: macOS 10.13.6
version:0.2.10
=====
Mac :: ~/ProductiveTools/SnippetStore » npm audit

                       === npm audit security report ===

# Run  npm update cryptiles --depth 4  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Insufficient Entropy                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ cryptiles                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ universal-analytics                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ universal-analytics > request > hawk > cryptiles             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/720                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

found 1 high severity vulnerability in 42614 scanned packages
  run `npm audit fix` to fix 1 of them.

**Comment by magussiro** [comment]
update electron to 1.8.8 , and update universal-analytics to 0.4.20 can fix this security issue

**Comment by ZeroX-DG** [comment]
Dependency updated! Thank you for reporting :+1:
