### ISSUE TITLE
[Suggestion] Add About SnippetStore menu

### ISSUE THREAD

**Issue by bantya** [ZeroX-DG/SnippetStore#33]
⭕ Please add a **About SnippetStore** menu item to the **Help** menu.

![image](https://user-images.githubusercontent.com/16685565/51437203-0cc4ca00-1cc1-11e9-88d0-2c35f51e2694.png)

e.g. which may contain something like:

![image](https://user-images.githubusercontent.com/16685565/51437457-aa6dc880-1cc4-11e9-89dd-1f48d86cea32.png)

⭕ Also having **Check for updates** menu item certainly would not hurt. 😉

**Comment by ZeroX-DG** [comment]
Thank you for your suggestion, I'll add this as soon as I can.

**Comment by ZeroX-DG** [comment]
DONE! Available in v0.2.11
