### ISSUE TITLE
[Imprevement] The tooltip styling

### ISSUE THREAD

**Issue by bantya** [ZeroX-DG/SnippetStore#34]
The edit snippet and save snippet button tooltips are bit off (font, font-size etc.) compared to other UI elements.

![image](https://user-images.githubusercontent.com/16685565/51564584-b2d92580-1eb5-11e9-8079-98601a200c9d.png)

Please look into it. 

🙂

**Comment by ZeroX-DG** [comment]
Fixed in https://github.com/ZeroX-DG/SnippetStore/pull/35
