### ISSUE TITLE
Editing Markdown in preview mode is broken.

### ISSUE THREAD

**Issue by bantya** [ZeroX-DG/SnippetStore#37]
## Current Behavior

Clicking the edit button in current Markdown preview implementation does not work. It does not go to the edit mode, but shows the `apply` and `cancel` buttons. The preview area freezes. Clicking the `apply` edit button does nothing. Clicking the `cancel` edit button crashes the app. To make the app responsive again, had to `reload` it manually.

## Demonstration

![md_edit_problem](https://user-images.githubusercontent.com/16685565/52743001-0cd59280-2fff-11e9-9603-5380e9a5c36f.gif)

## Expected Behavior

Editing the Markdown snippet during preview mode should take it directly to edit mode. All the editing and the buttons should work as normal.

## System Info

![sys_info](https://user-images.githubusercontent.com/16685565/52743172-6e95fc80-2fff-11e9-98d4-b0156bf71d12.png)

**Comment by ZeroX-DG** [comment]
Fixed in [64b74cc](https://github.com/ZeroX-DG/SnippetStore/commit/64b74cc2dd18e429c75a55249094ac60f5c1b0e1)
