### ISSUE TITLE
Markdown preview is not consistent.

### ISSUE THREAD

**Issue by bantya** [ZeroX-DG/SnippetStore#38]
## Current Behavior

When previewing a Markdown if another Markdown snippet is clicked, the preview does not update with the selected snippet. It just freezes and keeps showing the first selected snippet preview.

## Demonstration

![md_preview_freeze](https://user-images.githubusercontent.com/16685565/52743608-67bbb980-3000-11e9-8ea3-5eb50707df9b.gif)

## Expected Behavior

While previewing a Markdown if another Markdown snippet is selected, the preview should update according to the content of **selected** Markdown snippet. For choosing a non-Markdown snippet in-between, it should open that one in normal mode.

## System Info

![image](https://user-images.githubusercontent.com/16685565/52743645-7904c600-3000-11e9-9e73-9148524f2eb0.png)

**Comment by ZeroX-DG** [comment]
Fixed in [0d3ab7d](https://github.com/ZeroX-DG/SnippetStore/commit/0d3ab7dde76035a175cb41e09fa25a8cdc51ed0d)
