### ISSUE TITLE
No way to preview GitHub Flavoured Markdown snippets.

### ISSUE THREAD

**Issue by bantya** [ZeroX-DG/SnippetStore#39]
## Current Behavior

The preview button does not show up for GitHub Flavoured Markdown. Thus can't preview GFM.

## Demonstration

![md_git_md_preview](https://user-images.githubusercontent.com/16685565/52743801-e0bb1100-3000-11e9-8352-f182794e93b1.gif)

## Expected Behavior

The preview button should appear for GitHub Flavoured Markdown and should work normal as like simple Markdown.

## System Info

![image](https://user-images.githubusercontent.com/16685565/52743804-e284d480-3000-11e9-9dc5-a124767f271f.png)

**Comment by ZeroX-DG** [comment]
Fixed in [9dec808](https://github.com/ZeroX-DG/SnippetStore/commit/9dec808806509fc3d4de4d70064f0205b8ed5130)
