### ISSUE TITLE
Can't open links from Markdown preview area.

### ISSUE THREAD

**Issue by bantya** [ZeroX-DG/SnippetStore#40]
## Current Behavior

Clicking the links in current Markdown preview implementation does not work. Upon clicking, the preview area goes blank and nothing happens.

## Demonstration

![md_link_not_opening](https://user-images.githubusercontent.com/16685565/52743898-1a8c1780-3001-11e9-948e-f3ae76db1fdc.gif)

## Expected Behavior

Clicking on the link should open that link in the default browser.

## System Info

![image](https://user-images.githubusercontent.com/16685565/52743902-1c55db00-3001-11e9-8ded-05152e1277e6.png)

**Comment by ZeroX-DG** [comment]
Fixed in [4864b8b](https://github.com/ZeroX-DG/SnippetStore/tree/4864b8be1bb09fb3951d089eca0b4b1a9a8fcbb5). Thanks for reporting!
