### ISSUE TITLE
how to uninstall SnippetStore in Linux

### ISSUE THREAD

**Issue by arcturus140** [ZeroX-DG/SnippetStore#45]
I installed the app via appimage. How can I remove it from my system?

I removed it from Ubuntu Software manager but the config files in `~/.config` are still there...
I am using Ubuntu 16.04.

1. uninstall via software manager
2. `rm -rf ~/.config/Snippetstore`
3. `rm -rf ~/.config/snippetstore`
4. `rm ~/.local/share/applications/appimagekit-snippetstore.desktop`

**Comment by ZeroX-DG** [comment]
I think that's it, you won't have to delete anything else.

**Comment by arcturus140** [comment]
I added point 4, seems complete.
