### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by no1san** [ZeroX-DG/SnippetStore#56]
Hi,
maybe it is just a user problem but:
How do I add any Tag to my snippet?

**Comment by ZeroX-DG** [comment]
Hi, you can click edit on your snippet and type in the tags in the input next to the tag icon

**Comment by no1san** [comment]
Thanks for your fast reply.
I tried that. I can enter a tag however they are not saved.

**Comment by Echowxsy** [comment]
> Thanks for your fast reply.
> I tried that. I can enter a tag however they are not saved.

maybe you need type a blank after type tag name

**Comment by ndsamuelson** [comment]
> > Thanks for your fast reply.
> > I tried that. I can enter a tag however they are not saved.
> 
> maybe you need type a blank after type tag name

This is correct. I wasn't able to duplicate the issue. Try re-installing. 💪

**Comment by i-ce-fish** [comment]
You should press TAB after input a  tag

**Comment by ZeroX-DG** [comment]
I can't reproduce the issue either. I'll close this issue thanks for reporting anyway :+1:
