### ISSUE TITLE
Exporting/Importing database of snippet

### ISSUE THREAD

**Issue by Tsunaze** [ZeroX-DG/SnippetStore#7]
When we want to switch computers, we can't find all the snippets saved. Even if it's not online or anything, exporting the DB could be a great feature. Or for sharing with others (in a team)

**Comment by ZeroX-DG** [comment]
Thank you for your suggestion, I'm planing on making export to json file feature and import through json file. But that's just a temporary solution, in the future you can store your snippet on gist too.

**Comment by ZeroX-DG** [comment]
Fixed in v0.2.6
