### ISSUE TITLE
Let the user choose save location for all snippets 

### ISSUE THREAD

**Issue by TobiasDev** [ZeroX-DG/SnippetStore#9]
I love this tool. I haven't used it for long, but I love a tool that currently only saves my snippets locally. :) However, something that would for me personally would be awesome to add is that I can choose in which folders it should save all my snippets. That way I could store it in my Dropbox, OneDrive, etc. and when I install it on a new PC just change it to load from that folder and all my snippets would show up on both my desktop and laptop. 

Another even more awesome, but I think more complicated way, would be to add WebDav support, so I can set-up a WebDav connection to a folder where it syncs all my things. Kind of like how Joplin (Evernote replacement that is Open-Source does it). That way I could sync it through my own local NextCloud server and wouldn't have to worry about the privacy of Dropbox and such as well. Like I wrote though, I think that is more complicated, but still wanted to throw it out there.

**Comment by ZeroX-DG** [comment]
Thank you for suggesting this feature, I'll implement it soon. And I'll try researching on WebDav too :smile:

**Comment by ZeroX-DG** [comment]
Fix em in the latest release v0.2.6
